### ISSUE TITLE
Error applying configuration

### ISSUE THREAD

**Issue by ZombaL85** [roeldev/iac-talos-cluster#1]
Hi, I'm trying to use your code to create a cluster on proxmox but I'm getting errors with vda disks.
And actually the disks are not created, any help ?

pve-manager/8.1.5

![image](https://github.com/roeldev/iac-talos-cluster/assets/84121923/e0cba21e-3b43-4b7e-be3c-2632dbc3672a)

```│ Error: Error applying configuration
│ 
│   with talos_machine_configuration_apply.control-planes["0"],
│   on talos-boot.tf line 29, in resource "talos_machine_configuration_apply" "control-planes":
│   29: resource "talos_machine_configuration_apply" "control-planes" {
│ 
│ rpc error: code = InvalidArgument desc = configuration validation failed: 1 error occurred:
│       * specified install disk does not exist: "/dev/vda"
│ 
│ 
╵
╷
│ Error: Error applying configuration
│ 
│   with talos_machine_configuration_apply.worker-nodes["2"],
│   on talos-boot.tf line 58, in resource "talos_machine_configuration_apply" "worker-nodes":
│   58: resource "talos_machine_configuration_apply" "worker-nodes" {
│ 
│ rpc error: code = InvalidArgument desc = configuration validation failed: 1 error occurred:
│       * specified install disk does not exist: "/dev/vda"

**Comment by roeldev** [comment]
Can you post your `tfvars` file?

**Comment by ZombaL85** [comment]
Yes sure:
```
proxmox_api_url = "https://192.168.1.100:8006/api2/json"
proxmox_api_token_id = "apiuser"
proxmox_api_token_secret = "apitoken"
cluster_vip = "192.168.1.101"
proxmox_servers = {
  pve1 = {
    control_planes_count = 1
    disk_storage_pool    = "local-lvm"
    network_bridge       = "vmbr0"
    node_labels          = {
      role = "control-plane"
    }
  }
}
talos_worker_nodes = [
  {
    target_server = "pve1"
    node_labels = {
      role = "worker"
    }
    count = 1
      }
    ]
```

**Comment by roeldev** [comment]
It appears, as far as I can tell, your vars are correct. Are there no other errors/warnings in the terraform output?

**Comment by ZombaL85** [comment]
```
│ Warning: Argument is deprecated
│
│   with proxmox_vm_qemu.talos-control-plane["0"],
│   on vm-control-plane.tf line 13, in resource "proxmox_vm_qemu" "talos-control-plane":
│   13: resource "proxmox_vm_qemu" "talos-control-plane" {
│
│ Use `disks` instead
│
│ (and one more similar warning elsewhere)

```
I read that the way of managing disks has changed from disk to disks in one of the versions of Proxmox.

**Comment by roeldev** [comment]
I see https://github.com/Telmate/terraform-provider-proxmox has a new rc. I'll switch back to that provider instead of TheGameProfi/proxmox (which is also now archived). I'll see if I can make a commit later today.

**Comment by roeldev** [comment]
Unfortunately I won't be able to update to the new telmate version as they have changed the way disks can be configured in a bad, not dynamic way: https://github.com/Telmate/terraform-provider-proxmox/issues/907. This will probably kill my homelab automation (I'm not running the latest Proxmox 8.1 version) and I'm just not willing to risk that.

**Comment by ZombaL85** [comment]
I'm looking for a solution to adapt your code to the new method of disk provisioning.

**Comment by roeldev** [comment]
Good news, I was able to fix this issue by switching to the `bpg/proxmox` provider.
I tested it with the latest proxmox release (8.2.2) and talos 1.7.1.

**Comment by outbackdingo** [comment]
@roeldev switching to bpg/proxmox ???
